baseURL = "https://swasher.github.io/games/"
defaultContentLanguage = "en"
title = "Games Backlog"
theme = "blowfish"

enableRobotsTXT = true
summaryLength = 0

buildDrafts = false
buildFuture = false
enableEmoji = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5
