backend:
  name: github
  repo: swasher/games
  branch: master
  base_url: "https://decap-cms-proxy.mr-swasher.workers.dev"
  auth_endpoint: "auth"
  # login: true
  auth_type: pkce
#  redirect_uri: "https://swasher.github.io/games/admin/"
  #  site_id: swasher.github.io/games
#  site_domain: "swasher.github.io/games"

media_folder: ""        # для page bundles: сохранять рядом с index.md
public_folder: ""

publish_mode: editorial_workflow

site_url: "https://swasher.github.io/games"
display_url: "https://swasher.github.io/games"
search: false

collections:
  - name: "planned"
    label: "Planned"
    files:
      - name: "index"
        label: "Planned Page"
        file: "content/planned/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
          - { label: "Show Table of Contents", name: "toc", widget: "boolean", default: true }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "done"
    label: "Done"
    files:
      - name: "index"
        label: "Done Page"
        file: "content/done/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
          - { label: "Show Table of Contents", name: "toc", widget: "boolean", default: true }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "completed"
    label: "Completed"
    files:
      - name: "index"
        label: "Completed Page"
        file: "content/completed/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
          - { label: "Show Table of Contents", name: "toc", widget: "boolean", default: true }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "rejected"
    label: "Rejected"
    files:
      - name: "index"
        label: "Rejected Page"
        file: "content/rejected/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
          - { label: "Show Table of Contents", name: "toc", widget: "boolean", default: true }
          - { label: "Body", name: "body", widget: "markdown" }
